# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-20 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NNModelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_date', models.DateTimeField()),
                ('user_created', models.CharField(max_length=50)),
                ('company_created', models.CharField(max_length=50)),
                ('input_size', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('optim_func', models.CharField(choices=[('mape', 'mape'), ('mse', 'mse'), ('mae', 'mae')], max_length=50)),
                ('loss_func', models.CharField(choices=[('sgd', 'sgd'), ('rmsprop', 'rmsprop'), ('adam', 'adam')], max_length=50)),
                ('epoch_size', models.IntegerField()),
                ('num_layers', models.IntegerField()),
                ('weights_json', models.CharField(max_length=500)),
                ('min_train_err', models.FloatField()),
                ('data_file', models.FileField(upload_to='uploads/data/')),
            ],
        ),
    ]
