# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nnmodelhistory',
            name='model_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
