# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0002_nnmodelhistory_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nnmodelhistory',
            name='num_neurons_layer_str',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
