# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0004_auto_20180620_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='NNJobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50)),
                ('job_start_time', models.DateTimeField()),
                ('job_end_time', models.DateTimeField()),
                ('job_status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('SUCCEED', 'SUCCEED')], max_length=50)),
                ('user_created', models.CharField(max_length=50)),
            ],
        ),
    ]
