# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0005_nnjobhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nnmodelhistory',
            name='current_data_header',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
