# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-01 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0008_auto_20180629_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnmodelhistory',
            name='data_file_path',
            field=models.FilePathField(blank=True, default=None, null=True, path='/Users/whliu/Documents/work/github/web/webtrainer/src/com/django/django/webtrainer/uploads/data'),
        ),
    ]
