# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0012_auto_20180709_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='nnjobhistory',
            name='model_name',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nnjobhistory',
            name='weights_json',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
