# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0014_auto_20180709_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnmodelhistory',
            name='data_file_path',
            field=models.FilePathField(blank=True, default=None, null=True, path='E:\\work\\web\\webtrainer\\webtrainer\\src\\django\\webtrainer\\uploads\\data'),
        ),
    ]
