# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0007_nnmodelhistory_data_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nnmodelhistory',
            name='data_file',
        ),
        migrations.AddField(
            model_name='nnmodelhistory',
            name='data_file_path',
            field=models.FilePathField(blank=True, default=None, null=True, path='uploads/data/'),
        ),
    ]
