# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0009_auto_20180701_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='nnmodelhistory',
            name='target_col_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nnmodelhistory',
            name='data_file_path',
            field=models.FilePathField(blank=True, default=None, null=True, path='C:\\Users\\d891834\\Projects\\temp\\webtrainer\\src\\com\\django\\django\\webtrainer\\uploads\\data'),
        ),
    ]
