# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-08 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0011_auto_20180708_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnjobhistory',
            name='job_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nnjobhistory',
            name='job_status',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('SUCCEED', 'SUCCEED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nnmodelhistory',
            name='data_file_path',
            field=models.FilePathField(blank=True, default=None, null=True, path='C:\\Users\\d891834\\Projects\\temp\\webtrainer\\src\\com\\django\\django\\webtrainer\\uploads\\data'),
        ),
    ]
