# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNModelManager', '0013_auto_20180709_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnmodelhistory',
            name='loss_func',
            field=models.CharField(choices=[('mape', 'mape'), ('mse', 'mse'), ('mae', 'mae')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nnmodelhistory',
            name='optim_func',
            field=models.CharField(choices=[('sgd', 'sgd'), ('rmsprop', 'rmsprop'), ('adam', 'adam')], max_length=50),
        ),
    ]
