# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-08 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_current_selected_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_running_job_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
