# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180429_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_selected_model_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
